import '@/assets/styles/globals.css';
import '@/assets/styles/reset.css';
import StoreProvider from '@/store/StoreProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang='en'>
        <body className={inter.className}>
          <div className='wrapper'>
            <main>{children}</main>
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
