import '@/assets/styles/globals.css';
import '@/assets/styles/reset.css';
import Providers from '@/providers/Providers';
import { Layout } from 'antd';
import { Content, Footer, Header } from 'antd/es/layout/layout';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang='en'>
        <body className={inter.className}>
          <Layout style={{ minHeight: '100%' }}>
            <Header></Header>
            <Content>{children}</Content>
            <Footer></Footer>
          </Layout>
        </body>
      </html>
    </Providers>
  );
}
